services:
  express:
    build: ./express
    volumes:
      - ./express:/usr/src/app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql
    command: npm run dev
  svelte:
    build: ./svelte
    volumes:
      - ./svelte:/usr/src/app
    ports:
      - "8080:5173"
    tty: true
    depends_on:
      - mysql
    command: npm run dev
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/.data:/var/lib/mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
